# Generated by Django 4.2.3 on 2023-07-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50, verbose_name='Имя команды')),
                ('answer', models.TextField(verbose_name='Ответ бота')),
            ],
            options={
                'verbose_name': 'Команда для бота',
                'verbose_name_plural': 'Команды для бота',
            },
        ),
    ]
